export enum JOINT_TYPE {
    FILL = 0,
    JOINT_CAP_BUTT = 2,
    JOINT_CAP_SQUARE = 4,
    JOINT_CAP_ROUND = 6,
    JOINT_BEVEL = 8,
    JOINT_MITER = 12,
    JOINT_ROUND = 16,
    CAP_BUTT = 20,
    CAP_SQUARE = 22,
    CAP_ROUND = 24,
}
